spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5436/cooling
    username: admin
    password: admin
  kafka:
    bootstrap-servers: localhost:29092



